version: "3.9"

services:
  sentiment-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    env_file:
      - .env.production
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-w", "4", "-b", "0.0.0.0:7860", "src.api.main:app"]
